# Generated by Django 3.2.6 on 2022-04-04 11:31

from django.db import migrations


def fill_category_fk(apps, schema_editor):
    Article = apps.get_model('blog', 'Article')
    Category = apps.get_model('blog', 'Category')
    for sample in Article.objects.all():
        sample.category_fk, created = Category.objects.get_or_create(
            title=sample.category)
        sample.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220404_1601'),
    ]

    operations = [
        migrations.RunPython(fill_category_fk),
    ]
