# Generated by Django 3.2.6 on 2022-04-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220404_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name="category_fk",
            new_name='category',
        ),
    ]
